export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const FETCHING_DATA_SUBJECT = 'FETCHING_DATA_SUBJECT'
export const FETCHING_DATA_SUCCESS_SUBJECT = 'FETCHING_DATA_SUCCESS_SUBJECT'
export const FETCHING_DATA_FAILURE_SUBJECT = 'FETCHING_DATA_FAILURE_SUBJECT'


export const FETCHING_DATA_REGISTER_SUBJECT = 'FETCHING_DATA_REGISTER_SUBJECT'
export const FETCHING_DATA_SUCCESS_REGISTER_SUBJECT = 'FETCHING_DATA_SUCCESS_REGISTER_SUBJECT'
export const FETCHING_DATA_FAILURE_REGISTER_SUBJECT = 'FETCHING_DATA_FAILURE_REGISTER_SUBJECT'
export const FETCHING_DATA_CHANGECHECK_REGISTER_SUBJECT = 'FETCHING_DATA_CHANGECHECK_REGISTER_SUBJECT'